//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerValidatingTimeslot.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerValidatingTimeslotEntities : DbContext
    {
        public SchedulerValidatingTimeslotEntities()
            : base("name=SchedulerValidatingTimeslotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SchedulerValidatingTimeslotCategory> Categories { get; set; }
        public DbSet<SchedulerValidatingTimeslotCustomerDemographic> CustomerDemographics { get; set; }
        public DbSet<SchedulerValidatingTimeslotCustomer> Customers { get; set; }
        public DbSet<SchedulerValidatingTimeslotEmployee> Employees { get; set; }
        public DbSet<SchedulerValidatingTimeslotIntraday> Intradays { get; set; }
        public DbSet<SchedulerValidatingTimeslotMeetingAtendee> MeetingAtendees { get; set; }
        public DbSet<SchedulerValidatingTimeslotMeeting> Meetings { get; set; }
        public DbSet<SchedulerValidatingTimeslotOrder_Detail> Order_Details { get; set; }
        public DbSet<SchedulerValidatingTimeslotOrder> Orders { get; set; }
        public DbSet<SchedulerValidatingTimeslotProduct> Products { get; set; }
        public DbSet<SchedulerValidatingTimeslotRegion> Regions { get; set; }
        public DbSet<SchedulerValidatingTimeslotShipper> Shippers { get; set; }
        public DbSet<SchedulerValidatingTimeslotSupplier> Suppliers { get; set; }
        public DbSet<SchedulerValidatingTimeslotTask> Tasks { get; set; }
        public DbSet<SchedulerValidatingTimeslotTerritory> Territories { get; set; }
        public DbSet<SchedulerValidatingTimeslotWeather> Weathers { get; set; }
    }
}
