//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerValidatingTimeslot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerValidatingTimeslotTask
    {
        public SchedulerValidatingTimeslotTask()
        {
            this.Tasks1 = new HashSet<SchedulerValidatingTimeslotTask>();
        }
    
        public int TaskID { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public bool IsAllDay { get; set; }
        public string RecurrenceRule { get; set; }
        public Nullable<int> RecurrenceID { get; set; }
        public string RecurrenceException { get; set; }
        public string StartTimezone { get; set; }
        public string EndTimezone { get; set; }
    
        public virtual ICollection<SchedulerValidatingTimeslotTask> Tasks1 { get; set; }
        public virtual SchedulerValidatingTimeslotTask Task1 { get; set; }
    }
}
