//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerValidatingTimeslot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerValidatingTimeslotShipper
    {
        public SchedulerValidatingTimeslotShipper()
        {
            this.Orders = new HashSet<SchedulerValidatingTimeslotOrder>();
        }
    
        public int ShipperID { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<SchedulerValidatingTimeslotOrder> Orders { get; set; }
    }
}
