//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridEditing3LevelHierarchy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GridEditing3LevelHierarchyEntities : DbContext
    {
        public GridEditing3LevelHierarchyEntities()
            : base("name=GridEditing3LevelHierarchyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GridEditing3LevelHierarchyEmployee> Employees { get; set; }
        public virtual DbSet<GridEditing3LevelHierarchyOrder_Detail> Order_Details { get; set; }
        public virtual DbSet<GridEditing3LevelHierarchyOrder> Orders { get; set; }
        public virtual DbSet<GridEditing3LevelHierarchyProduct> Products { get; set; }
    }
}
