//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerEditingCustomEditor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerEditingCustomEditorEntities : DbContext
    {
        public SchedulerEditingCustomEditorEntities()
            : base("name=SchedulerEditingCustomEditorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SchedulerEditingCustomEditorMeetingAttendee> MeetingAttendees { get; set; }
        public DbSet<SchedulerEditingCustomEditorMeeting> Meetings { get; set; }
    }
}
