//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridEditingPopUpMultiSelect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GridEditingPopUpMultiSelectEntities : DbContext
    {
        public GridEditingPopUpMultiSelectEntities()
            : base("name=GridEditingPopUpMultiSelectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GridEditingPopUpMultiSelectEmployee> Employees { get; set; }
        public virtual DbSet<GridEditingPopUpMultiSelectTerritory> Territories { get; set; }
    }
}
