//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridMasterDetail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridMasterDetailCategory
    {
        public GridMasterDetailCategory()
        {
            this.Products = new HashSet<GridMasterDetailProduct>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<GridMasterDetailProduct> Products { get; set; }
    }
}
