//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.EditorDatabaseImageBrowser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.ChildFolders = new HashSet<Folder>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Path { get; set; }
    
        public virtual ICollection<Folder> ChildFolders { get; set; }
        public virtual Folder Parent { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
