//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerDragAndDrop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchedulerDragAndDropEntities : DbContext
    {
        public SchedulerDragAndDropEntities()
            : base("name=SchedulerDragAndDropEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SchedulerDragAndDropMeetingAttendee> MeetingAttendees { get; set; }
        public DbSet<SchedulerDragAndDropMeeting> Meetings { get; set; }
    }
}
