//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridHierarchyClientDetailTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GridHierarchyClientDetailTemplateEntities : DbContext
    {
        public GridHierarchyClientDetailTemplateEntities()
            : base("name=GridHierarchyClientDetailTemplateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GridHierarchyClientDetailTemplateCategory> Categories { get; set; }
        public virtual DbSet<GridHierarchyClientDetailTemplateProduct> Products { get; set; }
    }
}
