//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridEditingPopUpNestedGridBatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GridEditingPopUpNestedGridBatchEntities : DbContext
    {
        public GridEditingPopUpNestedGridBatchEntities()
            : base("name=GridEditingPopUpNestedGridBatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GridEditingPopUpNestedGridBatchEmployee> Employees { get; set; }
        public virtual DbSet<GridEditingPopUpNestedGridBatchOrder_Detail> Order_Details { get; set; }
        public virtual DbSet<GridEditingPopUpNestedGridBatchOrder> Orders { get; set; }
    }
}
