//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.ODataWebApiWrappers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODataWebApiWrappersEntities : DbContext
    {
        public ODataWebApiWrappersEntities()
            : base("name=ODataWebApiWrappersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ODataWebApiWrappersCategory> Categories { get; set; }
        public virtual DbSet<ODataWebApiWrappersEmployee> Employees { get; set; }
        public virtual DbSet<ODataWebApiWrappersProduct> Products { get; set; }
    }
}
