//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.GridHierarchyInCellEditing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GridHierarchyInCellEditingEntities : DbContext
    {
        public GridHierarchyInCellEditingEntities()
            : base("name=GridHierarchyInCellEditingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GridHierarchyInCellEditingEmployee> Employees { get; set; }
        public virtual DbSet<GridHierarchyInCellEditingOrder> Orders { get; set; }
    }
}
