//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telerik.Examples.Mvc.Areas.SchedulerServerFiltering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingAtendee
    {
        public int MeetingID { get; set; }
        public int AtendeeID { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
